/*CREACIÓN DE TABLAS*/

DROP DATABASE IF EXISTS `MYDAL`;
CREATE DATABASE `MYDAL` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
--
-- SELECCIONAMOS PARA USAR
--
USE `MYDAL`;
--
-- DAMOS PERMISO USO Y BORRAMOS EL USUARIO QUE QUEREMOS CREAR POR SI EXISTE
--
GRANT USAGE ON * . * TO `MYDAL`@`localhost`;
	DROP USER `MYDAL`@`localhost`;

--
-- CREAMOS EL USUARIO Y LE DAMOS PASSWORD,DAMOS PERMISO DE USO Y DAMOS PERMISOS SOBRE LA BASE DE DATOS.
--
CREATE USER IF NOT EXISTS `mydalUser`@`localhost` IDENTIFIED BY 'mydal19';
GRANT USAGE ON *.* TO `mydalUser`@`localhost` REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `MYDAL`.* TO `mydalUser`@`localhost` WITH GRANT OPTION;
--
-- Estructura de tabla para la tabla `datos`
--

CREATE TABLE IF NOT EXISTS USUARIO(
	ID_USUARIO INT(10) AUTO_INCREMENT,
	USERNAME VARCHAR(255) NOT NULL,
	PASSWD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO)

)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS CARPETA(

	ID_CARPETA INT(10) AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    PROPIETARIO INT(10) NOT NULL,
    PADRE INT(10),

	CONSTRAINT FK_PROPIETARIO FOREIGN KEY(PROPIETARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
	CONSTRAINT PK_CARPETA PRIMARY KEY(ID_CARPETA)

)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

ALTER TABLE CARPETA ADD FOREIGN KEY(PADRE) REFERENCES CARPETA(ID_CARPETA) ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS FICHERO(
	ID_FICHERO INT(10) AUTO_INCREMENT,
	NOMBRE VARCHAR(255) NOT NULL,
    PROPIETARIO INT(10) NOT NULL,
    PADRE INT(10),
	FORMATO VARCHAR(255) NOT NULL,
	COMPARTIR ENUM("SI","NO"),
	UUID binary(16) not null,

	CONSTRAINT FK_PADRE FOREIGN KEY(PADRE) REFERENCES CARPETA(ID_CARPETA) ON DELETE CASCADE,
	CONSTRAINT UN_UUID UNIQUE(UUID),
	CONSTRAINT PK_FICHERO PRIMARY KEY(ID_FICHERO)

)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;


